from base_robot_mr_wiskers_2 import BaseRobot
from pybricks.parameters import Stop
harold = BaseRobot()
harold.frontMotor.run_target(300,75,wait=False)
harold.db.straight(70)
harold.db.turn(92)
harold.db.straight(475)
harold.frontMotor.run_until_stalled(-300)
harold.db.straight(-200)
harold.db.turn(-29)
harold.db.straight(95)
harold.frontMotor.run_target(270,80,wait=False)
# harold.db.curve(-100,70)
# harold.db.curve(100,-130)
harold.db.straight(-250)